services:
  # Python AI Service
  - type: web
    name: chat-ai-service
    plan: free
    runtime: python
    buildCommand: pip install -r ai-service/requirements.txt
    startCommand: cd ai-service && gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
        
  - type: web
    name: chatal-backend
    env: dotnet
    plan: free
    rootDirectory: backend/ChatAlBackend
    buildCommand: dotnet restore && dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/ChatAlBackend.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:8080
