services:
  # .NET Backend Service
  - type: web
    name: chat-backend
    plan: free
    runtime: docker
    dockerfilePath: backend/ChatAIBackend/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: AIServiceUrl
        value: https://chat-ai-service.onrender.com/analyze

  # Python AI Service - FIXED
  - type: web
    name: chat-ai-service
    plan: free
    runtime: python
    buildCommand: cd ai-service && pip install -r requirements.txt
    startCommand: cd ai-service && gunicorn app:app --bind 0.0.0.0:$PORT